#!/usr/bin/env bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    echo "Creating 'website' directory structure."
    NAME="website"
else
    NAME=$1
    echo "Creating '${NAME}' directory structure."
fi

mkdir $NAME
cd $NAME
echo "${NAME}/"
touch index.html
echo "index.html"
touch stylesheet.css
echo "stylesheet.css"
mkdir imgs
echo "${NAME}/imgs/"
